/*
  # Classify non-HTTP audit events as automated system activity

  Direct SQL migrations, scheduled database work, and service-role writes do
  not have an originating browser IP. They must not be presented as anonymous
  customer-dashboard activity.
*/

CREATE OR REPLACE FUNCTION public.set_audit_log_request_origin()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_headers jsonb := '{}'::jsonb;
  v_request_method text;
  v_has_http_request boolean;
  v_client_info text;
  v_surface text;
  v_path text;
BEGIN
  BEGIN
    v_headers := COALESCE(NULLIF(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  EXCEPTION WHEN OTHERS THEN
    v_headers := '{}'::jsonb;
  END;

  v_request_method := NULLIF(current_setting('request.method', true), '');
  v_has_http_request := v_headers <> '{}'::jsonb OR v_request_method IS NOT NULL;

  -- Older versions of the row-audit trigger used "customer" as the fallback
  -- for every request without an authenticated user. Correct that fallback
  -- while the audit row is being created.
  IF NEW.actor_user_id IS NULL AND COALESCE(NEW.actor_role, '') = 'customer' THEN
    NEW.actor_role := CASE
      WHEN auth.role() = 'anon' THEN 'anonymous'
      WHEN auth.role() = 'service_role' OR NOT v_has_http_request THEN 'system'
      ELSE NEW.actor_role
    END;
  END IF;

  v_client_info := COALESCE(v_headers ->> 'x-client-info', '');
  v_surface := substring(v_client_info FROM 'bank-surface=([a-z_]+)');
  v_path := substring(v_client_info FROM 'bank-path=([^; ]+)');

  IF NOT v_has_http_request THEN
    v_surface := 'system';
    v_path := NULL;
  ELSIF v_surface IS NULL OR v_surface NOT IN ('crm_admin', 'customer_dashboard', 'authentication', 'public_site') THEN
    v_surface := CASE
      WHEN NEW.category = 'auth' THEN 'authentication'
      WHEN NEW.actor_role IN ('admin', 'superior_manager', 'agent') THEN 'crm_admin'
      WHEN NEW.actor_role = 'customer' THEN 'customer_dashboard'
      WHEN NEW.actor_role = 'system' THEN 'system'
      ELSE 'unknown'
    END;
  END IF;

  NEW.source_surface := v_surface;
  NEW.source_path := NULLIF(left(COALESCE(v_path, ''), 300), '');
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.set_audit_log_request_origin() FROM PUBLIC, anon, authenticated;

-- Correct legacy rows generated by migrations and other direct database work.
UPDATE public.audit_logs
SET
  actor_role = 'system',
  source_surface = 'system',
  source_path = NULL
WHERE actor_user_id IS NULL
  AND actor_name IS NULL
  AND actor_email IS NULL
  AND actor_ip IS NULL
  AND actor_role = 'customer'
  AND source_surface = 'customer_dashboard';

COMMENT ON FUNCTION public.set_audit_log_request_origin() IS
  'Classifies the initiating application surface and distinguishes HTTP requests from direct system/database work.';

NOTIFY pgrst, 'reload schema';
