/*
  # Comprehensive application audit trail

  Captures every INSERT, UPDATE, and DELETE on the current public application
  tables, plus explicit authentication events. Audit records are immutable to
  application users and visible only to full CRM administrators.
*/

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  event_type text NOT NULL,
  category text NOT NULL CHECK (category IN (
    'auth', 'users', 'balances', 'transactions', 'transfers',
    'payments', 'loans', 'settings', 'other'
  )),
  table_name text NOT NULL,
  record_id text,
  subject_user_id uuid,
  subject_name text,
  subject_email text,
  actor_user_id uuid,
  actor_name text,
  actor_email text,
  actor_role text,
  actor_ip text,
  summary text NOT NULL,
  changed_fields text[] NOT NULL DEFAULT ARRAY[]::text[],
  old_data jsonb,
  new_data jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS audit_logs_occurred_at_idx
  ON public.audit_logs (occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_category_occurred_at_idx
  ON public.audit_logs (category, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_actor_user_id_idx
  ON public.audit_logs (actor_user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_subject_user_id_idx
  ON public.audit_logs (subject_user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_table_name_idx
  ON public.audit_logs (table_name, occurred_at DESC);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.audit_logs FROM anon, authenticated;
GRANT SELECT ON TABLE public.audit_logs TO authenticated;

DROP POLICY IF EXISTS "Admins can view audit logs" ON public.audit_logs;
CREATE POLICY "Admins can view audit logs"
  ON public.audit_logs
  FOR SELECT
  TO authenticated
  USING (public.is_admin_user());

CREATE OR REPLACE FUNCTION public.audit_category_for_table(p_table_name text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT CASE
    WHEN p_table_name IN ('profiles', 'kyc_submissions') THEN 'users'
    WHEN p_table_name IN ('fiat_balances', 'crypto_balances', 'balance_snapshots') THEN 'balances'
    WHEN p_table_name IN ('transactions', 'crypto_transactions', 'currency_exchanges') THEN 'transactions'
    WHEN p_table_name IN ('bank_transfers', 'crypto_transfers', 'interac_transfers', 'scheduled_transfers') THEN 'transfers'
    WHEN p_table_name IN ('cards', 'bill_payments', 'taxes', 'tax_summary_cards', 'tax_wallet_addresses') THEN 'payments'
    WHEN p_table_name IN ('loans', 'fixed_deposits', 'crypto_deposits', 'staking_positions') THEN 'loans'
    WHEN p_table_name IN (
      'site_branding', 'crm_ip_allowlist_settings', 'interac_access_settings',
      'tax_bank_payment_settings'
    ) THEN 'settings'
    ELSE 'other'
  END;
$$;

CREATE OR REPLACE FUNCTION public.redact_audit_data(p_data jsonb)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT CASE
    WHEN p_data IS NULL THEN NULL
    ELSE p_data - ARRAY[
      'password', 'plain_password', 'password_hash', 'encrypted_password',
      'cvv', 'pin', 'card_number', 'security_answer', 'access_token',
      'refresh_token', 'token', 'secret', 'private_key', 'navbar_logo_url',
      'footer_logo_url', 'favicon_urls'
    ]
  END;
$$;

CREATE OR REPLACE FUNCTION public.capture_row_audit_log()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old jsonb := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END;
  v_new jsonb := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END;
  v_row jsonb := COALESCE(v_new, v_old, '{}'::jsonb);
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_actor_email text;
  v_actor_role text;
  v_subject_user_id uuid;
  v_subject_name text;
  v_subject_email text;
  v_changed_fields text[] := ARRAY[]::text[];
  v_record_id text;
BEGIN
  IF TG_TABLE_NAME = 'audit_logs' THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;

  IF v_actor_id IS NOT NULL THEN
    SELECT profile.full_name, profile.email, public.get_crm_role(profile.id)
    INTO v_actor_name, v_actor_email, v_actor_role
    FROM public.profiles AS profile
    WHERE profile.id = v_actor_id;
  END IF;

  BEGIN
    v_subject_user_id := COALESCE(
      NULLIF(v_row ->> 'user_id', '')::uuid,
      CASE WHEN TG_TABLE_NAME = 'profiles' THEN NULLIF(v_row ->> 'id', '')::uuid ELSE NULL END
    );
  EXCEPTION WHEN invalid_text_representation THEN
    v_subject_user_id := NULL;
  END;

  IF TG_TABLE_NAME = 'profiles' THEN
    v_subject_name := NULLIF(v_row ->> 'full_name', '');
    v_subject_email := NULLIF(v_row ->> 'email', '');
  ELSIF v_subject_user_id IS NOT NULL THEN
    SELECT NULLIF(profile.full_name, ''), NULLIF(profile.email, '')
    INTO v_subject_name, v_subject_email
    FROM public.profiles AS profile
    WHERE profile.id = v_subject_user_id;
  END IF;

  v_record_id := COALESCE(
    NULLIF(v_row ->> 'id', ''),
    NULLIF(v_row ->> 'reference_number', ''),
    NULLIF(v_row ->> 'user_id', '')
  );

  IF TG_OP = 'UPDATE' THEN
    SELECT COALESCE(array_agg(keys.key ORDER BY keys.key), ARRAY[]::text[])
    INTO v_changed_fields
    FROM (
      SELECT COALESCE(old_values.key, new_values.key) AS key
      FROM jsonb_each(v_old) AS old_values
      FULL JOIN jsonb_each(v_new) AS new_values USING (key)
      WHERE old_values.value IS DISTINCT FROM new_values.value
    ) AS keys;

    IF cardinality(v_changed_fields) = 0 THEN
      RETURN NEW;
    END IF;
  ELSIF TG_OP = 'INSERT' THEN
    SELECT COALESCE(array_agg(key ORDER BY key), ARRAY[]::text[])
    INTO v_changed_fields
    FROM jsonb_object_keys(v_new) AS keys(key);
  ELSIF TG_OP = 'DELETE' THEN
    SELECT COALESCE(array_agg(key ORDER BY key), ARRAY[]::text[])
    INTO v_changed_fields
    FROM jsonb_object_keys(v_old) AS keys(key);
  END IF;

  INSERT INTO public.audit_logs (
    event_type,
    category,
    table_name,
    record_id,
    subject_user_id,
    subject_name,
    subject_email,
    actor_user_id,
    actor_name,
    actor_email,
    actor_role,
    actor_ip,
    summary,
    changed_fields,
    old_data,
    new_data,
    metadata
  ) VALUES (
    lower(TG_OP),
    public.audit_category_for_table(TG_TABLE_NAME),
    TG_TABLE_NAME,
    v_record_id,
    v_subject_user_id,
    v_subject_name,
    v_subject_email,
    v_actor_id,
    NULLIF(v_actor_name, ''),
    NULLIF(v_actor_email, ''),
    COALESCE(v_actor_role, CASE WHEN auth.role() = 'service_role' THEN 'system' ELSE 'customer' END),
    CASE
      WHEN public.request_client_ip() IS NULL THEN NULL
      ELSE host(public.request_client_ip())
    END,
    CASE lower(TG_OP)
      WHEN 'insert' THEN 'Created a record in ' || replace(TG_TABLE_NAME, '_', ' ')
      WHEN 'update' THEN 'Updated a record in ' || replace(TG_TABLE_NAME, '_', ' ')
      ELSE 'Deleted a record from ' || replace(TG_TABLE_NAME, '_', ' ')
    END,
    v_changed_fields,
    public.redact_audit_data(v_old),
    public.redact_audit_data(v_new),
    jsonb_build_object('schema', TG_TABLE_SCHEMA, 'trigger_depth', pg_trigger_depth())
  );

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.audit_category_for_table(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.redact_audit_data(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.capture_row_audit_log() FROM PUBLIC, anon, authenticated;

DO $$
DECLARE
  v_table record;
BEGIN
  FOR v_table IN
    SELECT tables.tablename
    FROM pg_catalog.pg_tables AS tables
    WHERE tables.schemaname = 'public'
      AND tables.tablename NOT IN ('audit_logs', 'balance_snapshots')
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS audit_row_changes ON public.%I', v_table.tablename);
    EXECUTE format(
      'CREATE TRIGGER audit_row_changes AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_row_audit_log()',
      v_table.tablename
    );
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_auth_audit_event(
  p_event_type text,
  p_subject_email text DEFAULT NULL,
  p_subject_user_id uuid DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event text := lower(btrim(COALESCE(p_event_type, '')));
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_actor_email text;
  v_actor_role text;
  v_actor_ip text;
  v_summary text;
BEGIN
  IF v_event NOT IN ('signup_succeeded', 'signup_failed', 'login_succeeded', 'login_failed', 'logout') THEN
    RAISE EXCEPTION 'Unsupported authentication audit event.' USING ERRCODE = '22023';
  END IF;

  IF v_actor_id IS NOT NULL THEN
    SELECT profile.full_name, profile.email, public.get_crm_role(profile.id)
    INTO v_actor_name, v_actor_email, v_actor_role
    FROM public.profiles AS profile
    WHERE profile.id = v_actor_id;
  END IF;

  v_actor_ip := CASE
    WHEN public.request_client_ip() IS NULL THEN NULL
    ELSE host(public.request_client_ip())
  END;

  IF v_actor_id IS NULL AND (
    SELECT count(*)
    FROM public.audit_logs AS recent
    WHERE recent.category = 'auth'
      AND recent.actor_user_id IS NULL
      AND recent.actor_ip IS NOT DISTINCT FROM v_actor_ip
      AND recent.occurred_at > now() - interval '10 minutes'
  ) >= 30 THEN
    RETURN;
  END IF;

  v_summary := CASE v_event
    WHEN 'signup_succeeded' THEN 'User registration succeeded'
    WHEN 'signup_failed' THEN 'User registration failed'
    WHEN 'login_succeeded' THEN 'User signed in'
    WHEN 'login_failed' THEN 'Sign-in attempt failed'
    ELSE 'User signed out'
  END;

  INSERT INTO public.audit_logs (
    event_type,
    category,
    table_name,
    record_id,
    subject_user_id,
    subject_email,
    actor_user_id,
    actor_name,
    actor_email,
    actor_role,
    actor_ip,
    summary,
    metadata
  ) VALUES (
    v_event,
    'auth',
    'auth.users',
    COALESCE(p_subject_user_id, v_actor_id)::text,
    COALESCE(p_subject_user_id, v_actor_id),
    COALESCE(NULLIF(v_actor_email, ''), left(NULLIF(lower(btrim(p_subject_email)), ''), 320)),
    v_actor_id,
    NULLIF(v_actor_name, ''),
    COALESCE(NULLIF(v_actor_email, ''), left(NULLIF(lower(btrim(p_subject_email)), ''), 320)),
    COALESCE(v_actor_role, 'anonymous'),
    v_actor_ip,
    v_summary,
    jsonb_build_object(
      'source', left(COALESCE(NULLIF(p_metadata ->> 'source', ''), 'web_app'), 50)
    )
  );
END;
$$;

REVOKE ALL ON FUNCTION public.record_auth_audit_event(text, text, uuid, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_auth_audit_event(text, text, uuid, jsonb)
  TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.record_crm_audit_event(
  p_event_type text,
  p_subject_user_id uuid,
  p_summary text,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event text := lower(btrim(COALESCE(p_event_type, '')));
  v_actor_name text;
  v_actor_email text;
BEGIN
  IF NOT public.is_crm_staff() THEN
    RAISE EXCEPTION 'CRM staff access is required.' USING ERRCODE = '42501';
  END IF;

  IF v_event NOT IN ('user_created', 'user_deleted') THEN
    RAISE EXCEPTION 'Unsupported CRM audit event.' USING ERRCODE = '22023';
  END IF;

  SELECT profile.full_name, profile.email
  INTO v_actor_name, v_actor_email
  FROM public.profiles AS profile
  WHERE profile.id = auth.uid();

  INSERT INTO public.audit_logs (
    event_type,
    category,
    table_name,
    record_id,
    subject_user_id,
    subject_name,
    subject_email,
    actor_user_id,
    actor_name,
    actor_email,
    actor_role,
    actor_ip,
    summary,
    metadata
  ) VALUES (
    v_event,
    'users',
    'profiles',
    p_subject_user_id::text,
    p_subject_user_id,
    NULLIF(p_metadata ->> 'full_name', ''),
    NULLIF(p_metadata ->> 'email', ''),
    auth.uid(),
    NULLIF(v_actor_name, ''),
    NULLIF(v_actor_email, ''),
    public.get_crm_role(auth.uid()),
    CASE
      WHEN public.request_client_ip() IS NULL THEN NULL
      ELSE host(public.request_client_ip())
    END,
    left(COALESCE(NULLIF(btrim(p_summary), ''), 'Recorded a CRM user action'), 500),
    COALESCE(p_metadata, '{}'::jsonb) - ARRAY['password', 'plain_password', 'token', 'secret']
  );
END;
$$;

REVOKE ALL ON FUNCTION public.record_crm_audit_event(text, uuid, text, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_crm_audit_event(text, uuid, text, jsonb)
  TO authenticated;

COMMENT ON TABLE public.audit_logs IS
  'Immutable application audit trail. Sensitive authentication, card, and security fields are redacted.';
